language:
    python
python:
    - "3.5"

services:
    - postgresql

install:
    - cp contrib/env-sample .env
    - pip install -q -r requirements.txt

before_ script:
    - psql -c "CREATE DATABASE postgres;" -U postgres
    - psql -c "CREATE USER postgres WITH CREATEUSER PASSWORD 'postgres';" -U postgres
    - psql -c "ALTER USER postgres CREATEDB;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;" -U postgres

script:
    - python manage.py test