language:
    python
python:
    - "3.5"
install:
    - cp contrib/env-sample .env
    - pip install -q -r requirements.txt
script:
    - psql -c "CREATE DATABASE eventex_dev;" -U postgres
    - psql -c "CREATE USER eventex WITH PASSWORD 'eventex';" -U postgres
    - python manage.py test