language:
    python
python:
    - "3.5"
install:
    - cp contrib/env-sample .env
    - pip install -q -r requirements.txt
before_ script:
    - psql -c "CREATE DATABASE eventex_dev;" -U postgres
    - psql -c "CREATE USER eventex WITH CREATEUSER PASSWORD 'eventex';" -U postgres
    - psql -c "ALTER USER eventex CREATEDB;"
    - python manage.py test