language:
    python
python:
    - "3.5"

services:
    - postgresql

install:
    - cp contrib/env-sample .env
    - pip install -q -r requirements.txt

before_ script:
    - psql -c "CREATE DATABASE eventex_dev;"
    - psql -c "CREATE ROLE eventex WITH CREATEUSER PASSWORD 'eventex';"
    - psql -c "ALTER ROLE eventex CREATEDB;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE eventex_dev TO postgres;"
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE eventex_dev TO eventex;"


script:
    - python manage.py migrate
    - python manage.py test