version: '3'
services:

    frontend:
      image: nginx
      volumes:
        #site
        - ./eventex:/app
        - ./static:/app/static        
        #proxy
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:  
        - 80:80
      depends_on:
        - web

  
    web:
        build: . 
        image: eventex        
        volumes:
            - .:/app        
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        ports:
          - 8000:8000
          