# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170720_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('start', models.TimeField(verbose_name='início')),
                ('description', models.TextField(verbose_name='descrição')),
                ('slots', models.IntegerField()),
                ('speakers', models.ManyToManyField(to='core.Speaker')),
            ],
            options={
                'verbose_name': 'palestra',
                'abstract': False,
                'verbose_name_plural': 'palestras',
            },
        ),
    ]
